### PR TITLE
Adds ability to use mongoose query for synchronize

### PR DESCRIPTION
**Pull request by andfk**
Hi, i needed to include populated models data inside ES index in order to have data denormalised so in to achieve it directly from the `esSynchronise` I added the ability to use a Mongoose Query instead of adding more params to the method.

An example:
```
const query = User.find({ id: '....' }).populate('car', 'brand year').populate('city', 'name location')
User.esSynchronize(query).then(.....)
```

What do you think? I may need to add testing and proper info to the docs if you agree about this approach.

Thanks!

### CODE REVIEW

**Comment by nodkz** [comment]
I'd like this 👍

**Comment by jbdemonte** [comment]
Hi, thanks,
Could you add the unit test too please

**Comment by andfk** [comment]
Sure @jbdemonte as soon as I can I'll add the remaining stuff (tests and docs)

Thanks

**Comment by andfk** [comment]
Hi again. For some reason the some tests are failing on my local but the whole test set for esSynchronise fails. Reverted my changes and still fails so im lacking something I guess. Is the docker instance running a must to pass the CI?

**Comment by nodkz** [comment]
@andfk thanks a lot for improvement!
A new version will be published to npm automatically in several minutes.

**Comment by andfk** [comment]
Many thanks @nodkz!!

**Pull request merged**
